name: 'Setup and Build'
description: 'Reusable action to set up Node.js and build the project'
inputs:
  node-version-file:
    description: 'Path to the .node-version file'
    required: true
    default: '.node-version'

runs:
  using: 'composite'
  steps:
    - name: Get NodeJS Version
      id: node-version
      shell: bash
      run: echo "node-version=$(cat ${{ inputs.node-version-file }})" >> $GITHUB_OUTPUT

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ steps.node-version.outputs.node-version }}
        cache: 'npm'

    - name: Install dependencies
      shell: bash
      run: npm ci

    - name: Run build
      shell: bash
      run: npm run build
