name = "deck-gate"
main = "src/index.ts"
compatibility_date = "2025-04-01"

routes = [
  { pattern = "snocap.vc/deck*", zone_name = "snocap.vc" }
]

[[d1_databases]]
binding = "DB"
database_name = "deck-viewers"
database_id = "8a93ec28-acf4-434d-9b4c-33c2b44ba7bd"
