/**
 * Build-time sector list generation.
 *
 * Reads the choices of the "Sectors" multiple-select field from the
 * Applications table in Airtable (via the metadata API) and writes them to
 * src/data/sectors.ts, which the /apply form uses to power its <datalist>
 * suggestions.
 *
 * Requires a personal access token with the `schema.bases:read` scope,
 * supplied as AIRTABLE_TOKEN. If the token is missing or the request fails,
 * the existing committed src/data/sectors.ts is left untouched so builds keep
 * working offline / without secrets (matching scripts/generate-charts.mjs).
 */
import { readFile, writeFile } from "node:fs/promises";

const OUTPUT = new URL("../src/data/sectors.ts", import.meta.url).pathname;

// The Applications base / table / field that own the canonical sector list.
const BASE_ID = process.env.AIRTABLE_SECTORS_BASE ?? "appdWohIpZfsxvq0B";
const TABLE_ID = process.env.AIRTABLE_SECTORS_TABLE ?? "tblns5GpjFrtSV0OK";
const FIELD_NAME = process.env.AIRTABLE_SECTORS_FIELD ?? "Sectors";

async function main() {
  const token = process.env.AIRTABLE_TOKEN;
  if (!token) {
    console.warn(
      "[generate-sectors] AIRTABLE_TOKEN not set — keeping existing src/data/sectors.ts.",
    );
    return;
  }

  let res;
  try {
    res = await fetch(
      `https://api.airtable.com/v0/meta/bases/${BASE_ID}/tables`,
      { headers: { Authorization: `Bearer ${token}` } },
    );
  } catch (err) {
    console.warn(
      `[generate-sectors] Airtable request failed (${err.message}) — keeping existing src/data/sectors.ts.`,
    );
    return;
  }

  if (!res.ok) {
    console.warn(
      `[generate-sectors] Airtable returned ${res.status} — keeping existing src/data/sectors.ts.`,
    );
    return;
  }

  const data = await res.json();
  const table = data.tables?.find((t) => t.id === TABLE_ID);
  const field = table?.fields?.find((f) => f.name === FIELD_NAME);
  const choices = field?.options?.choices;

  if (!Array.isArray(choices) || choices.length === 0) {
    console.warn(
      `[generate-sectors] No choices found for ${TABLE_ID}.${FIELD_NAME} — keeping existing src/data/sectors.ts.`,
    );
    return;
  }

  // Dedupe (case-insensitive) and sort alphabetically for a tidy datalist.
  const seen = new Set();
  const sectors = choices
    .map((c) => c.name.trim())
    .filter((name) => {
      const key = name.toLowerCase();
      if (!name || seen.has(key)) return false;
      seen.add(key);
      return true;
    })
    .sort((a, b) => a.localeCompare(b));

  const contents = `// AUTO-GENERATED by scripts/generate-sectors.mjs — do not edit by hand.
// Source: Airtable base ${BASE_ID} table ${TABLE_ID} field "${FIELD_NAME}".
// Regenerate with: AIRTABLE_TOKEN=… npm run generate:sectors

export const sectors: string[] = [
${sectors.map((s) => `  ${JSON.stringify(s)},`).join("\n")}
];
`;

  const existing = await readFile(OUTPUT, "utf8").catch(() => null);
  if (existing === contents) {
    console.log(
      `[generate-sectors] src/data/sectors.ts already up to date (${sectors.length} sectors).`,
    );
    return;
  }

  await writeFile(OUTPUT, contents);
  console.log(
    `[generate-sectors] Wrote ${sectors.length} sectors to src/data/sectors.ts.`,
  );
}

main().catch((err) => {
  // Never fail the build over the sector list — log and move on.
  console.warn(`[generate-sectors] Unexpected error: ${err.message}`);
});
