name: Deploy to GitHub Pages

on:
  # Nightly, at midnight, to pull in new dynamic content
  schedule:
    - cron: "0 0 * * *"

  # Trigger deployment after the lint-and-build workflow completes
  workflow_run:
    workflows: ["Lint and Build"]
    branches: [main]
    types: [completed]

  # Allow manual triggers
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  HUSKY: 0

jobs:
  deploy:
    # Only run if the lint-and-build workflow succeeded or was manually triggered
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup and build
        uses: ./.github/workflows/setup
        with:
          node-version-file: ".node-version"

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  keepalive:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Keep workflow alive using GitHub API
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TIME_ELAPSED: 0
        run: |
          bash .github/scripts/keepalive.sh
