name: Lint and Build

on:
  push:
    branches:
      - main
      - next
env:
  HUSKY: 0

permissions:
  contents: write
  id-token: write

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup and build
        uses: ./.github/workflows/setup
        with:
          node-version-file: ".node-version"

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "engineering@cardless.com"
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

      - name: Run format
        run: npm run format

      - name: Check for changes
        id: git-check
        run: |
          git status --porcelain
          echo "changes=$(git status --porcelain | wc -l)" >> $GITHUB_OUTPUT

      - name: Commit and push if changes
        if: steps.git-check.outputs.changes != '0'
        run: |
          git add -A
          git commit -m "chore: lint and build"
          git push
          echo "Build canceled due to changes pushed."
          exit 0
